=== mattborja/identity/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "fingerprint": {
      "type": "string",
      "pattern": "^([A-F0-9]{32}|[A-F0-9]{40}|[A-F0-9]{64})$",
      "description": "Valid GPG fingerprint length (128-bit v3, 160-bit v4, or 256-bit v6), uppercased"
    },
    "label": {
      "type": "string",
      "description": "The label or name associated with the individual or entity, typically matching the name on the GPG key."
    },
    "validity": {
      "type": "string",
      "enum": [
        "full",
        "marginal",
        "revoked",
        "none"
      ],
      "description": "The validity level of the identity assertion. Indicates how thoroughly the identity has been verified.",
      "example": "full"
    },
    "refs": {
      "type": "array",
      "minItems": 2,
      "items": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date",
            "description": "The date when the verification or cross-signing took place, in YYYY-MM-DD format."
          },
          "comment": {
            "type": "string",
            "description": "A brief description of what the reference verifies or supports (e.g., project affiliation, key ownership)."
          },
          "artifact": {
            "type": "string",
            "description": "A cryptographic artifact (i.e. clearsigned message) demonstrating possession of a specific key (i.e. signing subkey)"
          },
          "url": {
            "type": "string",
            "format": "uri",
            "description": "A URL pointing to an authoritative source or resource that validates the reference."
          },
          "dns": {
            "type": "string",
            "pattern": "^[A-Za-z0-9]+\\._openpgpkey\\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$",
            "description": "Valid DNS domain name consisting of one or more labels (separated by dots), with each label containing only letters, numbers, and hyphens, and no label being longer than 63 characters. Provided for OPENPGPKEY DNS resource records (https://datatracker.ietf.org/doc/html/draft-ietf-dane-openpgpkey-06#section-2)."
          },
          "type": {
            "type": "string",
            "enum": [
              "role",
              "user",
              "key"
            ],
            "description": "The type of verification or evidence provided. 'role' is for project affiliation, 'user' signifies independent key ownership verification, and 'signature' indicates submission from private key holder"
          }
        },
        "required": [
          "date",
          "comment",
          "type"
        ],
        "additionalProperties": false
      },
      "description": "A list of references that provide evidence to support the identity assertion. Each reference must include a date, comment, and type."
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "A list of tags or labels that categorize or identify the individual or entity (e.g., 'OWASP', 'developer')."
      },
      "description": "Tags associated with the identity, which help categorize or identify the individual or entity."
    }
  },
  "required": [
    "fingerprint",
    "label",
    "validity",
    "refs",
    "tags"
  ],
  "additionalProperties": false
}

=== mattborja/identity/registry/99BB608E30380C451952D6BBA1C7E813F160A407.json
{
  "fingerprint": "99BB608E30380C451952D6BBA1C7E813F160A407",
  "label": "Matt Borja",
  "validity": "full",
  "refs": [
    {
      "date": "2024-11-27",
      "comment": "Signed artifact demonstrating private key use: `echo -n '3ED3 3CCE 4BED 165C 9107 3D9F 65B8 8DAC 23AF 5BCD E520 F723 C1E6 2A69 B369 F278' | gpg --clearsign --local-user D41A83E1C6B701619D0D812FC3F69D1BE6BCBD16`",
      "artifact": "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA512\n\n3ED3 3CCE 4BED 165C 9107 3D9F 65B8 8DAC 23AF 5BCD E520 F723 C1E6 2A69 B369 F278\n-----BEGIN PGP SIGNATURE-----\n\niHUEARYKAB0WIQTUGoPhxrcBYZ0NgS/D9p0b5ry9FgUCZ0dD0AAKCRDD9p0b5ry9\nFvonAQCHwAHRduopWn8I534GNRXQ0+dX5JO2ztnFxnlwZd+NMAD/Wr0NWLEc+eCf\nQm2UHkDp8lKswj6kXxTi9GI3elvpQgE=\n=L95q\n-----END PGP SIGNATURE-----\n",
      "type": "key"
    },
    {
      "date": "2024-10-06",
      "comment": "Cross-signed by F30FF4FC936584574EE3251833688C2EDC08CD38",
      "type": "user"
    },
    {
      "date": "2025-01-17",
      "comment": "Listed on LinkedIn profile as Download Public PGP Key link",
      "type": "user",
      "url": "https://www.linkedin.com/in/mattborja"
    },
    {
      "date": "2025-01-17",
      "comment": "LinkedIn profile showing identity verification by CLEAR using government ID",
      "type": "user",
      "url": "https://www.linkedin.com/help/linkedin/answer/a1359065"
    },
    {
      "date": "2025-01-01",
      "comment": "Industry certification requiring strong identity verification during proctored high stakes exam with Global Information Assurance Certification (https://www.giac.org/knowledge-base/proctor/)",
      "type": "user",
      "url": "https://www.credly.com/badges/c0ee1538-53dd-43a0-bf9e-7724e374ff43"
    },
    {
      "date": "2025-01-01",
      "comment": "Credly profile showing both user photo and industry certification with link to ORCiD profile (https://orcid.org/0009-0008-5528-9362)",
      "type": "user",
      "url": "https://www.credly.com/users/mattborja"
    },
    {
      "date": "2025-01-01",
      "comment": "OrciD profile referenced by Credly profile listing verified email domains, websites, social links, and GPG fingerprints in Keywords section using Uniform Resource Name format: urn:identity:gpg:<fingerprint>",
      "type": "user",
      "url": "https://orcid.org/0009-0008-5528-9362"
    }
  ],
  "tags": [
    "Self",
    "HSM"
  ]
}

=== mattborja/identity/registry/115DF9AEF857853EE8445D0A0727707EA15B79CC.json
{
  "fingerprint": "115DF9AEF857853EE8445D0A0727707EA15B79CC",
  "validity": "marginal",
  "label": "Fedora CoreOS Signing Key",
  "refs": [
    {
      "date": "2024-10-19",
      "comment": "Fedora CoreOS download page listing signing key(s) for downloads",
      "type": "role",
      "url": "https://fedoraproject.org/coreos/download?arch=x86_64#download_section"
    },
    {
      "date": "2025-01-28",
      "comment": "Vendor instructions for verifying GPG keys listing signing keys and OPENPGPKEY records (Fedora 40)",
      "type": "role",
      "url": "https://fedoraproject.org/security"
    },
    {
      "date": "2025-01-28",
      "comment": "Confirmed OPENPGPKEY DNS record existence (SOA) and fingerprint match",
      "type": "role",
      "dns": "4d0cd6e4349d5979387749daf5995f20d0de7f7b2fdfdc76d7eb21a1._openpgpkey.fedoraproject.org"
    }
  ],
  "tags": [
    "Fedora"
  ]
}

=== mattborja/identity/registry/21CB256AE16FC54C6E652949702D426D350D275D.json
{
  "fingerprint": "21CB256AE16FC54C6E652949702D426D350D275D",
  "label": "Rocky Enterprise Software Foundation - Release key 2022 <releng@rockylinux.org>",
  "validity": "full",
  "refs": [
    {
      "date": "2022-05-09",
      "comment": "Rocky Linux 9 Release Key",
      "artifact": "RPM-GPG-KEY-Rocky-9",
      "url": "https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-9",
      "type": "key"
    },
    {
      "date": "2023-01-17",
      "comment": "Independent verification of Rocky Linux 9 Release Key via archived sources",
      "url": "https://web.archive.org/web/20240331063950/https://rockylinux.org/keys/",
      "type": "key"
    },
    {
      "date": "2024-03-31",
      "comment": "Independent research techniques documented and referenced",
      "url": "https://github.com/mattborja/identity/pull/27#issue-2727122737",
      "type": "user"
    }
  ],
  "tags": [
    "Rocky Linux",
    "release key",
    "2022"
  ]
}
